//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BF2TV.WindowsApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class UserConfiguration : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserConfiguration defaultInstance = ((UserConfiguration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserConfiguration())));
        
        public static UserConfiguration Default {
            get {
                return defaultInstance;
            }
        }
    }
}
